### ISSUE TITLE
Bitwig, track displays not working

### ISSUE THREAD

**Issue by arnox747** [NicoG60/TouchMCU#1]
I know that Bitwig is not officially supported. I tried all the Mackie controller devices in Bitwig, and the Mackie "MCU - Control Universal" works great with the default template.
The only big issue is that no text is displayed in the top, blue track displays. I'd love some help figuring this out, since this is 99% close to perfect.

I also have a Behringer X-Touch One, and the displays work fine, and I have an original Mackie Control, but I'm not using it because I don't have the room for it.

**Comment by NicoG60** [comment]
Hi there 👋
That's interesting. So the LCD screen works using system exclusive messages.

There is 2 options I see here:
- the message is not transmitted. I know TouchOSC Bridge had a bug very recently where sysex messages were simply ignored. Make sure you use the latest version of that!
- The message itself should have a particular header - a couple of bytes at the begining with exact values describing the manufacturer and products the message is addressed to.
I suspect this header is slightly different from what my script expect and the messages are discarded.

Hunting the second point might be a little more involved but bear with me.

TouchOSC Editor have another product called [Protokol](https://hexler.net/protokol). It's a MIDI and OSC logger and it's free. Wonderful tool to debug communication. Could you try to install that, monitor TouchOSC MIDI in/out and watch out for sysex messages. Take a screenshot as soon as you see one and send it here so I can try to make sense of this.

Thanks

Nicolas

**Comment by arnox747** [comment]
Hi Nicolas!

Thank you for getting back to me so quickly, and solving the problem. My version of the Bridge was 172. Once I upgraded to the latest 173, the screens started working. This is now glorious!!!
Thanks again for putting this together. My plan is to use this on an iPad with the Behringer X-Touch Mini in MC mode. That might be the perfect controller for device parameters.

Not sure if you’ll get images, but below is the relevant Bitwig config, and the default template. Happy to send you whatever info you need, if you’d like to add Bitwig to the list of supported DAWs. I’ll also try it with Logic and Reaper.

Best,
-arno

**Comment by NicoG60** [comment]
Hi @arnox747 
the image you meant to send is not here I'm afraid!
I'll be happy to add bitwig to the supported platforms. It's cosmetic only as the protocol stays the same, just the text on the buttons changes. As long as I know which buttons does what...

If you feel like it, you can have a look in [this directory](https://github.com/NicoG60/TouchMCU/tree/main/touchmcu/overlays) which contains all the "translation" for the different DAWs. If you're comfortable enough making a bitwig one, feel free to open a PR!

Logic and Reaper might be good candidate as well, although they both have a native OSC support so it might be more efficient to use that directly, or apps like [Logic Remote](https://apps.apple.com/us/app/logic-remote/id638394624) which is even more appropriate.

Best
Nicolas

**Comment by arnox747** [comment]
I think the button mappings are spot on, but I’ll double-check and make a Bitwig template/PR if needed. Best, -arno
