### ISSUE TITLE
Bitwig - vu-meter works only on 1st audiochannel 

### ISSUE THREAD

**Issue by Knallebal** [NicoG60/TouchMCU#2]
i followed the guidlines to set this up for Bitwig.   everything works, but only the VU-meter on the first track is working, all other vu-meters don't work. is this because of limitations by bitwig   or did i misconfigure something?

**Comment by NicoG60** [comment]
Hi There, thanks for reaching out. I've noticed that issue recently as well, It's not Bitwig only, I'm using Cubase and am experiencing this issue. I didn't have the time to look into it yet but will do soon!

**Comment by NicoG60** [comment]
Hi @Knallebal 
I just fixed that Vu Meter bug. You can download the latest version of the layout 👉 [here](https://github.com/NicoG60/TouchMCU/releases/tag/v1.1) 👈 
Let me know if you're still experiencing this issue!

**Comment by Knallebal** [comment]
@NicoG60 Awesome!  truly Awesome!  thank you!

**Comment by NicoG60** [comment]
Let me know how it goes or if there is something I could improve in later releases. I'm a bit worried about performance as it's a quite busy layout, with scripting and all. Let me know if there's any performance issues

**Comment by Knallebal** [comment]
it goes like a train (as we say in dutch)  💯    it performs pretty well   no issu's on my old ipad2.  i want to buy you a beer.  if i had to mention 1 thing to improve your already-aswesome script, it would the length of the vu-meters   so that the vu-meters  would have the same length as the faders   a little more stretched

**Comment by NicoG60** [comment]
I'd be up for a pint ahah 🍺 

 I have a old iPad Gen 2 as well and it's a bit laggy for some reason, I'm glad it's not every old iPads the same, probably something on my end going wrong.

Good suggestion for the meters, I'll look into it when I have some time off!

**Comment by Knallebal** [comment]
i checked my ipad model.  i was wrong   it's an ipad air 1 (2013/2014)   i also tried to use it to fly my drone (dji mini2) but that's seems too much to ask of an ipad air 1.  the video feed stutters and even the dji-fly app warns about 100% cpu usage of the ipad.  so i use it only next to my ableton-push controller for music making purposes 😄
