### ISSUE TITLE
TouchMCU License 

### ISSUE THREAD

**Issue by topazcoding** [NicoG60/TouchMCU#6]
Hi Nico 

Can you please confirm the license for TouchMCU usage ?

best
Matt

**Comment by NicoG60** [comment]
I have just added a license file containing the terms of GPL 3
Does that answers your question?

**Comment by topazcoding** [comment]
Awesome, i've designed quite a big shortcut template for live and I was going to include a page/tab from your wonderful work.

Best Matt 😄
